apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: fluxcd
  annotations:
    fluxcd.io/ignore: "true"
spec:
  releaseName: sealed-secrets
  chart:
    repository: https://bitnami-labs.github.io/sealed-secrets
    name: sealed-secrets
    version: 1.8.0
